version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: event_ticketing_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: experion@123
      POSTGRES_DB: event_ticketing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-service:
    build: .
    container_name: event_ticketing_order_service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/event_ticketing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: experion@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8082

volumes:
  postgres_data:
