version: '3.8'
services:
  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: experion@123
      POSTGRES_DB: order_service_db
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  order-service:
    build: .
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: experion@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - order-db

volumes:
  order-db-data:
